/**
 * Import Vault E2E Test
 *
 * Tests the "I already have a Fast Vault" -> ImportVault flow.
 * Uses a pre-staged test vault file for Detox automation.
 *
 * In __DEV__ mode, the useImportFlow hook checks for a file named
 * `detox-import.vult` (or .bak) in the app's document directory and
 * auto-selects it when the user taps the file picker. This bypasses
 * the system file dialog that Detox cannot automate.
 *
 * Fixture: e2e/fixtures/test-vault.vult (encrypted, password: testpassword123)
 * Generated by: npx tsx e2e/fixtures/generate-test-vault.mts
 */
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const FIXTURE_PASSWORD = 'testpassword123';
const WRONG_PASSWORD = 'wrongpassword999';
const BUNDLE_ID = 'com.nicecode.vultisig';

const fixtureVult = path.resolve(__dirname, 'fixtures', 'test-vault.vult');
const fixtureBak = path.resolve(__dirname, 'fixtures', 'test-vault.bak');

/**
 * Stage a file in the simulator's app Documents directory.
 * The app's useImportFlow hook auto-detects files named `detox-import.*`
 * in Documents when running in __DEV__ mode.
 */
function stageFixture(udid, srcPath, destName) {
  const appContainer = execSync(
    `xcrun simctl get_app_container ${udid} ${BUNDLE_ID} data 2>/dev/null`,
    { encoding: 'utf8' },
  ).trim();
  const documentsDir = path.join(appContainer, 'Documents');
  execSync(`mkdir -p "${documentsDir}"`);
  fs.copyFileSync(srcPath, path.join(documentsDir, destName));
  console.log(`[Import] Staged ${destName} at ${documentsDir}`);
}

/** Erase simulator, boot, and launch app fresh. */
async function freshLaunch() {
  const udid = device.id;
  execSync(`xcrun simctl shutdown ${udid} 2>/dev/null; xcrun simctl erase ${udid}`, {
    timeout: 30000,
  });
  execSync(`xcrun simctl boot ${udid}`, { timeout: 30000 });
  await device.launchApp({ delete: true, newInstance: true });
  await device.disableSynchronization();
}

/** Navigate from app launch through RiveIntro to MigrationHome. */
async function navigateToMigrationHome() {
  try {
    await waitFor(element(by.id('enter-vultiverse-cta')))
      .toBeVisible()
      .withTimeout(10000);
    await element(by.id('enter-vultiverse-cta')).tap();
  } catch {
    // RiveIntro already transitioned
  }

  await waitFor(element(by.id('import-vault-button')))
    .toBeVisible()
    .withTimeout(90000);
}

/** Tap "Import Vault Share" on MigrationHome and reach ImportVault screen. */
async function navigateToImportScreen() {
  await element(by.id('import-vault-button')).tap();
  await waitFor(element(by.text('Import your vault share')))
    .toBeVisible()
    .withTimeout(10000);
}

describe('Import Vault', () => {
  // ─── Navigation ───────────────────────────────────────────────────
  describe('Navigation to ImportVault', () => {
    beforeAll(async () => {
      await freshLaunch();
    });

    afterAll(async () => {
      await device.enableSynchronization();
    });

    it('should reach MigrationHome', async () => {
      await navigateToMigrationHome();
    });

    it('should navigate to ImportVault screen', async () => {
      await navigateToImportScreen();
    });

    it('should show supported file types hint', async () => {
      await expect(element(by.text('Supported file types: .bak & .vult'))).toBeVisible();
    });

    it('should show the Continue button (disabled without a file)', async () => {
      await expect(element(by.id('import-continue'))).toBeVisible();
    });

    it('should navigate back to MigrationHome', async () => {
      await element(by.id('import-vault-back')).tap();
      await waitFor(element(by.id('import-vault-button')))
        .toBeVisible()
        .withTimeout(5000);
    });
  });

  // ─── .vult import with correct password ───────────────────────────
  describe('Import .vult with correct password', () => {
    beforeAll(async () => {
      const udid = device.id;
      execSync(`xcrun simctl shutdown ${udid} 2>/dev/null; xcrun simctl erase ${udid}`, {
        timeout: 30000,
      });
      execSync(`xcrun simctl boot ${udid}`, { timeout: 30000 });

      // Install app so we can stage files
      await device.launchApp({ delete: true, newInstance: true });
      await device.terminateApp();

      stageFixture(udid, fixtureVult, 'detox-import.vult');

      await device.launchApp({ newInstance: true });
      await device.disableSynchronization();
    });

    afterAll(async () => {
      await device.enableSynchronization();
    });

    it('should reach ImportVault screen', async () => {
      await navigateToMigrationHome();
      await navigateToImportScreen();
    });

    it('should auto-detect staged .vult file', async () => {
      await element(by.id('import-file-picker')).tap();
      await waitFor(element(by.text('detox-import.vult')))
        .toBeVisible()
        .withTimeout(10000);
    });

    it('should show password prompt for encrypted vault', async () => {
      await element(by.id('import-continue')).tap();
      await waitFor(element(by.id('decrypt-password-input')))
        .toBeVisible()
        .withTimeout(5000);
    });

    it('should decrypt and import with correct password', async () => {
      await element(by.id('decrypt-password-input')).typeText(FIXTURE_PASSWORD);
      await element(by.id('decrypt-continue')).tap();

      await waitFor(element(by.text('You are aboard, Station OG!')))
        .toBeVisible()
        .withTimeout(15000);
    });

    it('should pass vault integrity verification', async () => {
      await waitFor(element(by.id('verify-all-passed')))
        .toExist()
        .withTimeout(15000);
      await expect(element(by.id('verify-all-passed')))
        .toHaveText('all-passed: true');
    });

    it('should verify imported vault exists with correct name', async () => {
      await expect(element(by.id('verify-imported-exists')))
        .toHaveText('imported-exists: true');
      await expect(element(by.id('verify-imported-name')))
        .toHaveText('imported-name: true');
    });

    it('should verify imported vault has valid keyshare and pubkey', async () => {
      await expect(element(by.id('verify-imported-has-pubkey')))
        .toHaveText('imported-has-pubkey: true');
      await expect(element(by.id('verify-imported-has-keyshare')))
        .toHaveText('imported-has-keyshare: true');
    });

    it('should complete import and dismiss migration', async () => {
      await element(by.id('continue-button')).tap();
      await new Promise((r) => setTimeout(r, 2000));
    });
  });

  // ─── Persistence ──────────────────────────────────────────────────
  describe('Persistence — imported vault survives relaunch', () => {
    beforeAll(async () => {
      await device.launchApp({ newInstance: true });
      await device.disableSynchronization();
      await new Promise((r) => setTimeout(r, 3000));
    });

    afterAll(async () => {
      await device.enableSynchronization();
    });

    it('should not show migration flow on relaunch', async () => {
      let migrationShown = false;
      try {
        await waitFor(element(by.id('migration-cta')))
          .toBeVisible()
          .withTimeout(5000);
        migrationShown = true;
      } catch {
        // Expected — migration is complete
      }

      if (migrationShown) {
        throw new Error('Migration flow should not appear after successful import');
      }
    });
  });

  // ─── Wrong password ───────────────────────────────────────────────
  describe('Wrong password shows error', () => {
    beforeAll(async () => {
      const udid = device.id;
      execSync(`xcrun simctl shutdown ${udid} 2>/dev/null; xcrun simctl erase ${udid}`, {
        timeout: 30000,
      });
      execSync(`xcrun simctl boot ${udid}`, { timeout: 30000 });

      await device.launchApp({ delete: true, newInstance: true });
      await device.terminateApp();

      stageFixture(udid, fixtureVult, 'detox-import.vult');

      await device.launchApp({ newInstance: true });
      await device.disableSynchronization();
    });

    afterAll(async () => {
      await device.enableSynchronization();
    });

    it('should reach password prompt', async () => {
      await navigateToMigrationHome();
      await navigateToImportScreen();
      await element(by.id('import-file-picker')).tap();
      await waitFor(element(by.text('detox-import.vult')))
        .toBeVisible()
        .withTimeout(10000);
      await element(by.id('import-continue')).tap();
      await waitFor(element(by.id('decrypt-password-input')))
        .toBeVisible()
        .withTimeout(5000);
    });

    it('should show error for incorrect password', async () => {
      await element(by.id('decrypt-password-input')).typeText(WRONG_PASSWORD);
      await element(by.id('decrypt-continue')).tap();

      await waitFor(element(by.text('Incorrect password, try again')))
        .toBeVisible()
        .withTimeout(5000);
    });

    it('should keep password sheet open after error', async () => {
      await expect(element(by.id('decrypt-password-input'))).toBeVisible();
      await expect(element(by.id('decrypt-continue'))).toBeVisible();
    });
  });

  // ─── .bak file extension ─────────────────────────────────────────
  describe('Import .bak file extension', () => {
    beforeAll(async () => {
      const udid = device.id;
      execSync(`xcrun simctl shutdown ${udid} 2>/dev/null; xcrun simctl erase ${udid}`, {
        timeout: 30000,
      });
      execSync(`xcrun simctl boot ${udid}`, { timeout: 30000 });

      await device.launchApp({ delete: true, newInstance: true });
      await device.terminateApp();

      // Stage as .bak instead of .vult
      stageFixture(udid, fixtureBak, 'detox-import.bak');

      await device.launchApp({ newInstance: true });
      await device.disableSynchronization();
    });

    afterAll(async () => {
      await device.enableSynchronization();
    });

    it('should reach ImportVault screen', async () => {
      await navigateToMigrationHome();
      await navigateToImportScreen();
    });

    it('should auto-detect staged .bak file', async () => {
      await element(by.id('import-file-picker')).tap();
      await waitFor(element(by.text('detox-import.bak')))
        .toBeVisible()
        .withTimeout(10000);
    });

    it('should show password prompt for encrypted .bak vault', async () => {
      await element(by.id('import-continue')).tap();
      await waitFor(element(by.id('decrypt-password-input')))
        .toBeVisible()
        .withTimeout(5000);
    });

    it('should decrypt and import .bak file successfully', async () => {
      await element(by.id('decrypt-password-input')).typeText(FIXTURE_PASSWORD);
      await element(by.id('decrypt-continue')).tap();

      await waitFor(element(by.text('You are aboard, Station OG!')))
        .toBeVisible()
        .withTimeout(15000);
    });

    it('should pass vault integrity verification for .bak import', async () => {
      await waitFor(element(by.id('verify-all-passed')))
        .toExist()
        .withTimeout(15000);
      await expect(element(by.id('verify-all-passed')))
        .toHaveText('all-passed: true');
    });
  });
});
